Update README
inzva/Algorithm-Program pull request #62
Opened 2021-01-29 16:36 UTC by burakbugrul

### After this PR
The README file is now have more general information about the Algorithm Program.

2021-01-29 16:58 UTC, kayacanv requested changes

2021-01-29 16:58 UTC, kayacanv commented on README.md
> +Every Saturday. Every batch has a different date, we will be publishing the exact dates at [inzva.com](inzva.com) before every program.
every saturday yerine daha uzun bir cümle yazılabilir mi?
We usually meet on Saturdays during the program.

2021-01-29 16:58 UTC, kayacanv commented on README.md
> +We believe that the main benefit comes from the opportunity to practice with challenging problems. Here are some other benefits we think the participants will acquire from the program:
sadece practice with challanging problems yapmıyoruz ki program boyunca.

We believe that the main benefit comes from the opportunity to practice with challenging problems and taking a new step into the world of algorithms,
 yazılabilir.

2021-01-29 16:58 UTC, kayacanv commented on README.md
> -You can find the curriculum [here](https://docs.google.com/spreadsheets/d/1f5r41dZ5-khcHL9ba_b2TNCLMg0QCqG-cEMdqlkwmGM/edit#gid=521339157)
bir curriculum eklenmeli mi?

son programda kullandığımız curriculum buydu gibi bir bilgilendirme

2021-01-29 16:58 UTC, kayacanv commented on README.md
> +If you want to support the community as an **Editor, Problem Setter or Reviewer**, and get scholarship for your work by [BEV Foundation](https://bev.foundation/), you can sen an e-mail to contact@inz
Reviewerımız artık yok. reviewer kısmı değiştirilebilir

2021-01-29 16:59 UTC, kaplanbar requested changes

2021-01-29 16:59 UTC, kaplanbar commented on README.md
> +The participants are expected to not only have the skills, but also the enthusiasm and motivation for this unique program, which will be completely free of charge. The program will involve experience
"A minimum of %70 attendance.."
The minimum required attendance is 60% for the current program.

2021-01-29 16:59 UTC, kaplanbar commented on README.md
>  **HOW TO BE AN EDITOR/PROBLEM SETTER/REVIEWER**
Should we change this according to current program?
Otherwise you can skip this review.

Currently we do not have editors or reviewers. Should we update this to lecturer or something general like contributor?

2021-01-29 16:59 UTC, kaplanbar commented on README.md
> +The participants are expected to not only have the skills, but also the enthusiasm and motivation for this unique program, which will be completely free of charge. The program will involve experience
Should we change this according to current program?
Otherwise you can skip this review.

If yes, currently, there are no editors and reviewers since no new bundles are prepared. Maybe we can say something like "Lectures are delivered by experienced members of the inzva community on bundles prepared by the editors."

2021-01-29 16:59 UTC, kaplanbar commented on README.md
> +We prepared this full-fledged program to last all year in order to grow the algorithm community in its technical capacity and ready the students for international contests.
"...last all year..."

Current program is 15 weeks long.

2021-01-29 20:05 UTC, burakbugrul commented on README.md
> -You can find the curriculum [here](https://docs.google.com/spreadsheets/d/1f5r41dZ5-khcHL9ba_b2TNCLMg0QCqG-cEMdqlkwmGM/edit#gid=521339157)
Bence kafa karistirici olabilir, curriculum ve bundlelar farkli  biraz

2021-01-29 20:05 UTC, burakbugrul commented on README.md
> +If you want to support the community as an **Editor, Problem Setter or Reviewer**, and get scholarship for your work by [BEV Foundation](https://bev.foundation/), you can sen an e-mail to contact@inz
Editorumuz de olmuyor, ama gorev olarak asdece soru review vs etmek isteyen olur diye biraktim

2021-01-29 20:07 UTC, burakbugrul commented on README.md
> +If you want to support the community as an **Editor, Problem Setter or Reviewer**, and get scholarship for your work by [BEV Foundation](https://bev.foundation/), you can sen an e-mail to contact@inz
zorlama oldu siliyorum xD

2021-01-29 20:13 UTC, burakbugrul commented on README.md
>  **HOW TO BE AN EDITOR/PROBLEM SETTER/REVIEWER**
A deleted "REVIEWER", but don't we still need problem setters (yeah editor may be unnecessary but can leave it open)

2021-01-29 20:14 UTC, burakbugrul commented on README.md
> +We prepared this full-fledged program to last all year in order to grow the algorithm community in its technical capacity and ready the students for international contests.
Okey I changed it to 15 weeks for now but I doesn't reflect the general case. It changes every year maybe we could say something more generic

2021-01-29 21:53 UTC, kaplanbar commented
It seems fine for me. If you want, I can run grammarly on the text also and send it as a commit.

2021-01-29 21:54 UTC, kaplanbar approved these changes
It seems fine for me. If you want, I can run grammarly on the text and send it as commit.

2021-01-30 01:18 UTC, burakbugrul commented
> It seems fine for me. If you want, I can run grammarly on the text and send it as commit if we want perfection. 😄

Thanks for review, don't need to push grammarly I think :D

2021-01-31 11:25 UTC, merged